---
- name: Install or remove awscli
  package:
    name: awscli
    state: "{{ aws_cli_package_state }}"
  become: yes
  when: >
    ansible_distribution != 'Amazon'

- name: Install or remove aws-cli
  package:
    name: aws-cli
    state: "{{ aws_cli_package_state }}"
  become: yes
  when: >
    ansible_distribution == 'Amazon'

- name: Create aws cli configuration files
  block:
    - name: Set home directory to /root
      set_fact:
        aws_user_dir: /root/.aws
      when: >
        aws_cli_user == 'root'

    - name: Create aws cli directory
      file:
        path: "{{ aws_user_dir }}"
        state: directory
        owner: "{{ aws_cli_user }}"
        group: "{{ aws_cli_user_group }}"
        mode: 0700

    - name: Create aws cli config file
      template:
        src: aws_config.j2
        dest: "{{ aws_user_dir }}/config"
        owner: "{{ aws_cli_user }}"
        group: "{{ aws_cli_user_group }}"
        mode: 0600

    - name: Create aws cli credentials file
      template:
        src: aws_credentials.j2
        dest: "{{ aws_user_dir }}/credentials"
        owner: "{{ aws_cli_user }}"
        group: "{{ aws_cli_user_group }}"
        mode: 0600
  when:
    - profiles != None
    - profiles != [{}]
